import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const FantasyCardContent = ({ data, isBack }) => {
    if (isBack) {
        return (_jsxs("div", { className: "absolute inset-0 z-50 bg-[#081c15] flex items-center justify-center overflow-hidden", children: [_jsx("div", { className: "absolute inset-[-50%] opacity-20 rotate-[30deg]", style: {
                        backgroundImage: `url('/icons/hat_wizard.svg')`,
                        backgroundRepeat: "repeat",
                        backgroundSize: "45px 45px",
                    } }), _jsxs("div", { className: "relative z-10 flex flex-col items-center w-full px-8", children: [_jsx("div", { className: "w-24 h-24 mb-6 border-2 border-[var(--color-secondary)] rounded-full \n                                        flex items-center justify-center bg-[#081c15] shadow-[0_0_30px_rgba(255,201,113,0.3)]", children: _jsx("span", { className: "text-[var(--color-secondary)] text-6xl font-black", children: "?" }) }), _jsx("h2", { className: "text-[var(--color-secondary)] text-4xl font-black tracking-[0.2em] uppercase text-center drop-shadow-md", children: "Fantas\u00EDa" }), _jsxs("p", { className: "text-center text-xs font-medium italic text-[var(--color-secondary)]/60 mt-4 px-2", children: ["Puedes desvelar esta carta por ", _jsx("span", { className: "text-[var(--color-secondary)] px-1 rounded", children: "0M" }), ", pero si lo haces, ya no podr\u00E1s elegir la otra carta."] })] }), _jsx("div", { className: "absolute inset-4 border-2 border-[var(--color-secondary)]/10 shadow-[inset_0_0_15px_rgba(255,201,113,0.1)] pointer-events-none" })] }));
    }
    return (_jsx("div", { className: "w-full h-full bg-white border-2 border-black p-[12px] flex flex-col shadow-2xl", children: _jsxs("div", { className: "relative w-full h-full border-2 border-black flex flex-col bg-white overflow-hidden", children: [_jsx("div", { className: "h-20 border-b-2 border-black flex items-center justify-center p-2 shrink-0 bg-[var(--color-secondary)]", children: _jsx("h3", { className: "text-black font-black uppercase text-center text-lg leading-tight drop-shadow-sm", children: "FANTAS\u00CDA" }) }), _jsxs("div", { className: "p-5 flex-1 flex flex-col items-center text-center relative h-full", children: [_jsx("h2", { className: "font-black uppercase tracking-tighter mb-1 text-black text-2xl leading-none", children: data.title }), _jsx("div", { className: "w-full h-0.5 bg-black/10 my-2" }), _jsx("p", { className: "text-sm font-medium leading-relaxed text-gray-700 my-4 px-2", children: data.description }), data.card_cost !== undefined && (_jsxs("div", { className: "mt-auto pt-3 border-t-2 w-full border-dashed border-gray-300", children: [_jsx("p", { className: "text-[9px] font-black uppercase text-gray-400 mb-0.5 tracking-widest", children: "Valor de Compra" }), _jsxs("span", { className: "text-3xl font-black text-[var(--color-secondary)] leading-none", children: [data.card_cost, "M"] })] }))] })] }) }));
};
