import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const ServiceCardContent = ({ data }) => {
    if (data.isMortgaged) {
        return (_jsx("div", { className: "w-full h-full bg-white border-2 border-black p-[12px] flex flex-col shadow-2xl", children: _jsxs("div", { className: "relative w-full h-full border-[8px] border-[#e63946] flex flex-col bg-white items-center justify-between p-6 text-center overflow-hidden", children: [_jsx("div", { className: "absolute inset-0 opacity-[0.03] pointer-events-none", style: { backgroundImage: 'repeating-linear-gradient(45deg, #e63946 0, #e63946 1px, transparent 0, transparent 50%)',
                            backgroundSize: '10px 10px' } }), _jsxs("div", { className: "z-10 w-full", children: [_jsx("div", { className: "font-black text-[#e63946] text-xs uppercase tracking-[0.3em] mb-1", children: _jsx("h3", { children: data.typeName }) }), _jsx("h2", { className: "text-2xl font-black uppercase text-black leading-tight border-b-2 border-black pb-2 mx-4", children: data.name })] }), _jsxs("div", { className: "z-10 py-4 w-full", children: [_jsx("div", { className: "bg-[#e63946] text-white py-2 px-4 rotate-[-2deg] shadow-lg mb-4", children: _jsx("span", { className: "text-3xl font-black uppercase tracking-tighter", children: "Hipotecada" }) }), _jsxs("div", { className: "flex flex-col items-center", children: [_jsx("p", { className: "text-[10px] font-black uppercase text-gray-500 mb-1", children: "Hipotecado por" }), _jsxs("span", { className: "text-5xl font-black text-black tracking-tighter", children: [(data.buyPrice / 2), "M"] })] })] }), _jsx("div", { className: "z-10 w-full border-t border-gray-200 pt-4", children: _jsx("p", { className: "text-[11px] leading-tight text-gray-400 font-bold uppercase italic px-2", children: "\"Como esta casilla esta hipotecada, no hace falta pagar a su propietario\"" }) })] }) }));
    }
    return (_jsx("div", { className: "w-full h-full bg-white border-2 border-black p-[12px] flex flex-col shadow-2xl", children: _jsxs("div", { className: "relative w-full h-full border-2 border-black flex flex-col bg-white overflow-hidden", children: [_jsxs("div", { className: "h-24 border-b-2 border-black flex flex-col items-center justify-center p-2", children: [_jsx("span", { className: "text-[10px] text-black font-bold uppercase tracking-[0.15em] mb-0.5", children: data.typeName }), _jsx("h3", { className: "text-black font-black uppercase text-center text-xl leading-tight drop-shadow-sm", children: data.name })] }), _jsx("div", { className: "border-b-2 border-black flex justify-center items-center h-40 p-4", children: _jsx("img", { src: data.group === 13 || data.typeName === "Servidor"
                            ? "/images/server.png"
                            : "/icons/bridge.svg", alt: "tile icon", className: "max-h-full max-w-full object-contain" }) }), _jsxs("div", { className: "p-5 flex-1 flex flex-col items-center", children: [_jsxs("div", { className: "w-full mt-4 space-y-2 text-[20px] font-bold uppercase tracking-tight text-black", children: [_jsx("div", { className: "flex justify-center border-b border-black/10 pb-1 text-black font-black", children: _jsx("span", { children: "Alquileres" }) }), _jsxs("div", { className: "flex justify-between items-end text-gray-600 pt-6", children: [_jsxs("span", { className: "shrink-0", children: ["Con 1 ", data.typeName] }), _jsx("div", { className: "flex-1 border-b-2 border-dotted border-gray-400 mb-[5px] mx-2" }), _jsxs("span", { children: [data.rentPrices[0], "M"] })] }), _jsxs("div", { className: "flex justify-between items-end text-gray-600", children: [_jsxs("span", { className: "shrink-0", children: ["Con 2 ", data.typeName] }), _jsx("div", { className: "flex-1 border-b-2 border-dotted border-gray-400 mb-[5px] mx-2" }), _jsxs("span", { children: [data.rentPrices[1], "M"] })] })] }), _jsx("div", { className: "mt-auto w-full  pt-4 space-y-3", children: _jsxs("div", { className: "flex flex-col items-center border-t border-gray-300 pt-3", children: [_jsx("p", { className: "text-[10px] font-black uppercase text-gray-400 tracking-widest", children: "Valor de Hipoteca" }), _jsxs("span", { className: "text-xl font-black text-black", children: [data.buyPrice / 2, "M"] })] }) })] })] }) }));
};
